# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HieraGroup',
            fields=[
                ('group_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HieraMergeable',
            fields=[
                ('merge_parameter', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('default_value', models.BooleanField(default=False)),
                ('merges_parameter', models.CharField(max_length=50)),
            ],
        ),
    ]
